---
- hosts: localhost
  tasks:
  - amazon.aws.ec2_instance:
      key_name: default-ec2
      instance_type: t2.micro
      image_id: ami-041feb57c611358bd
      region: us-east-1
      security_group: "default"
      tags: 
        Environment: QA
      network:
            assign_public_ip: true
      wait: yes
      count: 1
    register: output_ec2
  - debug: var=output_ec2